### ISSUE TITLE
Remove the Travis block

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/glpk-feedstock#14]
We have a Travis [block of code](https://github.com/conda-forge/glpk-feedstock/blob/8af1b5679959ede0f15287b8726e8480d562b071/recipe/build.sh#L9-L11) in the recipe that is clearing away `brew`. We can drop this as that happens in the `.travis.yml` now before the build starts.

**Comment by dougalsutherland** [comment]
This was fixed by #22.

**Comment by jakirkham** [comment]
Thanks for the reminder. Hard to remember issues over years. :)
